[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.4"
gunicorn = {extras = ["gevent", "gthread"], version = "^23.0.0"}
uwsgi = "^2.0.28"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
