services:
  app:
    build: .
    working_dir: /opt
    tty: true
    entrypoint: ./entrypoint.sh
    volumes:
      - ./src:/opt
    ports:
      - 8000:8000
    environment:
      - PYTHONPATH=/opt
